# Generated by Django 4.2.5 on 2023-09-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('goal_amount', models.IntegerField()),
                ('category', models.CharField(choices=[('pendidikan', 'Pendidikan'), ('medis dan kesehatan', 'Medis dan Kesehatan'), ('lingkungan', 'Lingkungan'), ('bencana alam', 'Bencana Alam'), ('anak-anak', 'Anak-anak'), ('kemanusiaan', 'Kemanusiaan'), ('zakat', 'Zakat'), ('wakaf', 'Wakaf'), ('panti asuhan', 'Panti Asuhan'), ('hewan', 'Hewan')], default='pendidikan', max_length=100)),
                ('description', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
